### PR TITLE
cmssw benahcmarking tests

### PR DESCRIPTION
**Pull request by cerati**
Add build test of CMSSW TTbarPU35 to benchmarking scripts.

### CODE REVIEW

**Comment by cerati** [comment]
Plots: http://uaf-6.t2.ucsd.edu/~cerati/mictest/2016-06-15-PR55/

**Comment by kmcdermo** [comment]
@cerati cool!  Out of curiosity, how much longer does the benchmarking take with the cmssw building tests?

**Comment by cerati** [comment]
It took ~2h, I think it is not much different from before

**Comment by cerati** [comment]
some slides, just for reference (no need to present them):
https://dl.dropboxusercontent.com/u/13022849/compareCMSSW-noFWD-update.pdf

**Pull request merged**
