### PR TITLE
Endcap tests

### PR DESCRIPTION
**Pull request by cerati**
PR for endcap tracking.
Benchmarking plots coming soon.

### CODE REVIEW

**Comment by cerati** [comment]
Benchmarking http://uaf-6.t2.ucsd.edu/~cerati/mictest/2016-07-23-PR58/

Note that it takes much longer now since we have also tests in endcap. 
I guess there should be some slimming...

**Comment by osschar** [comment]
+1 @dan131riley please sign off, too

**Comment by dan131riley** [comment]
I suppose not surprisingly for two such extensive patches, #58 conflicts with @kmcdermo's #57.  The conflicts do look pretty trivial to resolve.  Normally I'd give priority to the earlier PR, but I don't know what @cerati's availability is to update #58; any suggestions?

**Comment by osschar** [comment]
As Kevin says ... it might be easier to get Giuseppe's in first this time.

**Comment by dan131riley** [comment]
#58 is merged, and I've requested that @kmcdermo update #57 so it merges with the new head.

**Pull request merged**
